[package]
name = "hls-rs"
version = "0.1.0"
authors = ["dr(bawb) <drbawb@fatalsyntax.com>"]

[dependencies]
clap = "2.32"
env_logger="0.5"
failure = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
